print('Seja bem vindo ao programa exemplo!')
print('---------------------------------------------------\n')
nome = input(' Seu nome')
print('\nOlá, %s. Farei algumas perguntas sobre vocẽ.' % nome)
idade = int(input('Qual a sua idade? '))
print('\nOk. vocẽ %d anos.' % idade)
altura = float(input('Qual a sua altura em metros? '))
print('\nVocẽ tem %.2f metros de altura.' % altura)
print('A idade do individuo e %d e a altura e %.2f' % (idade, altura))
print('\n\nIsso é tudo. Até a próxima, %s!' % nome)
print('---------------------------------------------------')